#! /bin/sh

~/.fehbg &
killall sxhkd; sxhkd &
killall picom; picom &
sh $HOME/.config/polybar/launch.sh &  # Starting up polybar

# BSPC Configuration
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         3
bspc config window_gap          16

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "#282828"
bspc config active_border_color "#ebdbb2"
bspc config focused_border_color "#fe8019"


# Application Rules
bspc rule -a Minecraft desktop='^3' state=floating follow=on
bspc rule -a CSGO state=fullscreen
bspc rule -a Screenkey manage=off
